org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.17.21

version=1.3.6+1.21.1
group=com.vnap

fabric_api_version=0.116.17+1.21.1
emf_version=FMPLuEEv
etf_version=lmZfRqnz
esf_version=Lh4AkFG5
modmenu_version=11.0.5

dialogue_test_command=false
