models.1=7
baby.1=true
models.2=2
name.2=iregex:(Mayor|Mayor Villager|The Mayor)
models.3=3
name.3=iregex:(Testificate Man)
models.4=4
name.4=iregex:(Villager Number 5|Villager #5)
models.5=5
name.5=iregex:(Villager Number 9|Villager #9)
models.6=6
name.6=iregex:(Villager Unreachable|Can't Catch Me!)
models.7=1
name.7=iregex:.*
